# Generated by Django 5.1.4 on 2024-12-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('detalhes', models.TextField()),
                ('data_servico', models.DateField()),
                ('data_entrega', models.DateField()),
                ('contato', models.CharField(max_length=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
