# Generated by Django 5.1.4 on 2024-12-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusinagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='servico',
            new_name='nomeservico',
        ),
    ]
