# Generated by Django 5.1.4 on 2024-12-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusinagem', '0003_rename_nomeservico_service_nome_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
