# Generated by Django 5.1.4 on 2024-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusinagem', '0004_service_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='Ativo', max_length=20),
        ),
    ]
