# Generated by Django 5.1.4 on 2024-12-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusinagem', '0005_remove_service_finalizado_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Finalizado', 'Finalizado')], max_length=20),
        ),
    ]
