# Generated by Django 5.1.4 on 2024-12-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusinagem', '0006_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Finalizado', 'Finalizado')], default='Ativo', max_length=20),
        ),
    ]
